#!/bin/bash
CONF_FOLDER=$(dirname $0)

cat $CONF_FOLDER/apt_get_installs | while read line 
do 
	
	sudo apt-get -y install $line
done 

sudo apt-get -y install lxde
sudo apt-get install xorg xserver-xorg

cp -r $CONF_FOLDER/tint2 $HOME/.config/
cp -r $CONF_FOLDER/openbox $HOME/.config/
mkdir $HOME/.themes; cp -r $CONF_FOLDER/themes/* $HOME/.themes
cp $CONF_FOLDER/vimconfigs/vimrc $HOME/.vimrc
mkdir $HOME/bin; cp $CONF_FOLDER/scripts/* $HOME/bin/

dconf reset -f /org/gnome/terminal/
dconf load /org/gnome/terminal/ < $CONF_FOLDER/gnome_terminal_backup

cp $CONF_FOLDER/bashrc $HOME/.bashrc

sudo snap install --classic slack
sudo snap install --classic vscode
#snap install chromium
sudo snap install spotify
sudo snap install discord

cat $CONF_FOLDER/vscode_extensions | while read line
do
	code --install-extension $line
done

cp -r $CONF_FOLDER/Wallpapers $HOME/Pictures/