#!/bin/bash
CONF_FOLDER=$(dirname $0)

cp -r $CONF_FOLDER/sources.list.d /etc/apt/

cat $CONF_FOLDER/manual_installs | while read line 
do 
	
	apt-get -y install $line
done 


cp -r $CONF_FOLDER/tint2 $HOME/.config/
cp -r $CONF_FOLDER/openbox $HOME/.config/
mkdir $HOME/.themes; cp -r $CONF_FOLDER/themes $HOME/.themes
cp $CONF_FOLDER/vimconfigs/vimrc $HOME/.vimrc
mkdir $HOME/bin; cp $CONF_FOLDER/scripts/* $HOME/bin/

dconf reset -f /org/gnome/terminal/
dconf load /org/gnome/terminal/ < $CONF_FOLDER/gnome_terminal_backup

cp $CONF_FOLDER/bashrc $HOME/.bashrc

snap install --classic slack
snap install --classic vscode
#snap install chromium
snap install spotify
snap install discord


